# Generated by Django 5.2.10 on 2026-04-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='REGISTERED', max_length=20)),
            ],
            options={
                'verbose_name': 'Activity Registration',
                'unique_together': {('user_id', 'activity_id')},
            },
        ),
    ]
