# Generated by Django 5.2.10 on 2026-02-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Activity Registration'},
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='registration_date',
            new_name='registered_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(default='REGISTERED', max_length=20),
        ),
    ]
